services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - 3310:3310
    env_file:
      - ./server/.env
    environment:
      - CLIENT_URL=http://localhost
    command: sh -c "npm run db:migrate:prod && node dist/src/main.js"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql/mysql-server:8.0
    ports:
      - 3306:3306
    env_file:
      - ./server/.env
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  db-data:
