FROM node:20-alpine as build-stage
WORKDIR /server
COPY package*.json ./
RUN npm install
COPY . .
RUN npx tsc

FROM node:20-alpine as production-stage
WORKDIR /server
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=build-stage /server/dist ./dist
EXPOSE 3000
CMD ["node", "dist/src/main.js"]
